### ISSUE TITLE
Code issues related to ./src/App.tsx

### ISSUE THREAD

**Issue by Misaka-0x447f** [Alendia/nekocolorpicker#1]
## https://github.com/Alendia/nekocolorpicker/blob/main/src/App.tsx#L10
Can be better with some library like https://www.npmjs.com/search?q=color+convert

## https://github.com/Alendia/nekocolorpicker/blob/842efcf70d4ee8483046d7c4bc273c3590ed9d48/src/App.tsx#L16
This line can be replace with `String.prototype.padStart`

## https://github.com/Alendia/nekocolorpicker/blob/main/src/App.tsx#L73
Seems like no reason to do that.

**Comment by Alendia** [comment]
Thanks for your advice.
https://github.com/Alendia/nekocolorpicker/blob/842efcf70d4ee8483046d7c4bc273c3590ed9d48/src/App.tsx#L10
This is not a function for converting HSL to RGB or similar conversions, so it could not use these libraries.

https://github.com/Alendia/nekocolorpicker/blob/842efcf70d4ee8483046d7c4bc273c3590ed9d48/src/App.tsx#L16
I think it's no need to do that, but I don't know this method before. 

https://github.com/Alendia/nekocolorpicker/blob/842efcf70d4ee8483046d7c4bc273c3590ed9d48/src/App.tsx#L73
I will remove it.
